name: "Build and publish Typst devcontainer to ghcr.io"

on:
  push:
    paths:
      - "templates/src/typst/Dockerfile"
      - "templates/src/typst/docker-bake.hcl"
      - ".github/workflows/containers-typst.yaml"
  workflow_dispatch:
  schedule:
    - cron: "0 2 1 4 *"  # historically, TeXLive has been published around March

jobs:
  build-push-typst:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Setup QEMU"
        uses: "docker/setup-qemu-action@v3"

      - name: "Setup Docker `buildx`"
        uses: "docker/setup-buildx-action@v3"

      - name: "Login to `ghcr.io`"
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - id: bake
        uses: docker/bake-action@v5
        with:
          workdir: "./templates/src/typst"
          push: true
