name: "Research (Docker Stacks): Build & Publish to ghcr.io"

on:
  push:
    paths:
      - "images/src/research/Dockerfile"
      - ".github/workflows/images-research.yaml"
  workflow_dispatch:

jobs:
  build-push-latex:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Setup QEMU"
        uses: "docker/setup-qemu-action@v3"

      - name: "Setup Docker `buildx`"
        uses: "docker/setup-buildx-action@v3"

      - name: "Login to `ghcr.io`"
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - id: versions
        run: |
          echo "DOCKER_STACKS_VERSION=$(date +'%Y-%m-%d')" >> "${GITHUB_OUTPUT}"

      - id: build-push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64,linux/amd64
          context: "./images/src/research"
          push: true
          tags:
            ghcr.io/jmuchovej/devcontainers/research:${{ steps.versions.outputs.DOCKER_STACKS_VERSION }}
