name: "LaTeX: Build & Publish to ghcr.io"

on:
  push:
    paths:
      - "images/src/latex/Dockerfile"
      - ".github/workflows/images-latex.yaml"
  workflow_dispatch:

jobs:
  build-push-latex:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Setup QEMU"
        uses: "docker/setup-qemu-action@v3"

      - name: "Setup Docker `buildx`"
        uses: "docker/setup-buildx-action@v3"

      - name: "Login to `ghcr.io`"
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - id: versions
        run: |
          v=$(grep "ARG TEXLIVE_VERSION=" images/src/latex/Dockerfile | awk '{print $2}')
          echo "${v}" >> "${GITHUB_OUTPUT}"

      - id: bake
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64,linux/amd64
          context: "./images/src/latex"
          push: true
          tags:
            ghcr.io/jmuchovej/devcontainers/latex:${{ steps.versions.outputs.TEXLIVE_VERSION }}
